name: .NET

on:
  push:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
    build-1:
        name: Build
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
          matrix:
            dotnet: ['8', '7']
            restore-rid: ['', '-r win-x64']
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: |
                    8.0.x
            - name: Restore dependencies
              run: dotnet restore --locked-mode ${{ matrix.restore-rid }}
            - name: Publish
              run: dotnet publish --no-restore -o pub --sc -f net${{ matrix.dotnet }}-windows10.0.22621.0